### ISSUE TITLE
Review how we create the name of the host_vars file as it contains invalid chars

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#145]
## Problem

Ansible reports this WARNING message

```
ansible-playbook ansible/playbook/post_installation.yml --tags k8s_cluster -e k8s_version=1.16.7 --limit n01-k116 -b               
[DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad characters in group names by default, this will change, but still be user configurable on deprecation. This feature will be removed in version 2.10. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to see details

[WARNING]: Found both group and host with same name: n01-k116

[WARNING]: Found both group and host with same name: n01-k116
```

Action items: 
- [ ]  Should we then rename the file `n01-k116` created under `ansible/inventory/host_vars` ?
- [ ] Should we also document what do to to avoid the warning `Found both group and host with same name: n01-k116` ?

@jacobdotcosta

**Comment by jacobdotcosta** [comment]
I think the problem is with group names, as groups shouldn't contain the minus character. That's why Ansible is complaining about ` Invalid characters were found in group names` (for instance, [this issue](https://github.com/ansible/ansible/issues/56930) ).

I suggest group names relate to some kind of functionality, because they provide resources for playbooks and roles as well as allow to filter to which hosts a playbook applies. For instance, we could have different hosts for k8s hosts, and a lower level indicating which version of k8s to be installed. This would be implemented with a hosts file and several group_vars files such as:

```
.../inventory/k8s_hosts
[masters:children]
k8s_115
k8s_116

[k8s_115]
host_01
host_02

[k8s_116]
host_03
host_04
```

Then in the each of the group_vars files, located at `.../inventory/groups_vars`

**masters**
`
firewall_ports: ...
firewall_services: ...
`

**k8s_115**
`
k8s_version: 1.15.10
`

**k8s_116**
`
k8s_version: 1.16.19
`

**Comment by cmoulliard** [comment]
Would the information be better organized if we use YAML syntax ? As this file will mainly be used by you and stored under gitlab, then we can adopt whatever solution you propose ;-)

**Comment by jacobdotcosta** [comment]
The hosts are now in the dynamic inventory. The groups var files are being documented in #148 .
