### ISSUE TITLE
Improve playbook to import/authorize ssh_key

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/k8s-infra#28]
To ssh as root to the vm `hetzner, local`, we use these commands to import our ssh_key as authorized key

```
sshpass -f pwd.txt ssh -o StrictHostKeyChecking=no root@127.0.0.1 -p 5222 "mkdir ~/.ssh && chmod 700 ~/.ssh && touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
sshpass -f pwd.txt ssh-copy-id -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pub root@127.0.0.1 -p 5222
```

We should improve the existing playbook to : 

- Create a generic private/public key and host it on a github repo
- Import the public ssh_key as authorized user within the target vm

Interesting articles : 

- http://blog.appliedinformaticsinc.com/how-to-manage-ssh-keys-using-ansible/
- [Authorize key](http://docs.ansible.com/ansible/latest/modules/authorized_key_module.html)
- [Generate ssh key and create user](http://docs.ansible.com/ansible/latest/modules/user_module.html)

**Comment by geoand** [comment]
I don't think this should be done for the following reasons:

For the case where we are creating VM for local development, the `new_iso.sh` script already grabs the host's keys (see https://github.com/snowdrop/cloud-native-infra/blob/9c358170b1c8157fa77f3172f0d16ef99a2f56da/virtualbox/build-centos-iso/cloud-init/new-iso.sh#L59) and imports them into the VM allowing the user to then perform password-less login into the VM without having to execute any additional command.

For the case where we want to install Openshift onto a cloud machine using our scripts, it would not be good to have a publicly accessible set of public/private keys, because then anyone could access the machine as a root user.

**Comment by davidjbrewer** [comment]
Feel free to look at https://github.com/eupraxialabs/tools and see if the ssh-import-id feature is something that can be worked into some of your use cases. See the section: "Special Tool in the Bag" The public image is at https://hub.docker.com/r/eupraxialabs/tools/

Clearly, you would want to parameterize the public key username in Ansible..

If we can be of any assistance, please let me know.

________________________________________

Other references: https://github.com/dustinkirkland/ssh-import-id

**Comment by geoand** [comment]
@davidjbrewer Thanks, I'll take a look when I have some time :)

**Comment by geoand** [comment]
@cmoulliard I propose we close this since we now have support for importing keys for GitHub.
